// Store data with prices
export const testStores = [
    {
        name: "Aldi Ogden Avenue",
        distance: 1.2,
        location: { lat: 41.795054238397235, lng: -88.1215363761931},
        prices: {
            flatLeafSpinach: 1.75,
            Coleslaw: 1.89,
            organicChoppedKale: 3.19,
            southwestChoppedSalad: 3.65,
            italianSalad: 2.85,
            springMix: 2.85,
            gardenSalad: 2.19,
            sweetKaleSaladKit: 3.65,
            caesarSaladKit: 3.29,
            asianChoppedSaladKit: 3.65,
            organicArugulaSpinachMix: 3.19,
            shreddedLettuce: 2.99,
            mangoSlices: 5.99,
            sweetButterSalad: 2.55,
            organicMixedGreens: 3.99,
            organicSpringMix: 5.39,
            organicBabySpinach: 3.19,
            sweetOnions: 2.99,
            carrots: 1.51,
            romaineLettuceHearts: 2.35,
            caramelApples: 3.99,
            papaya: 4.03,
            cucumber: .79,
            artisanLettuc: 3.55,
            babyCarrots: 1.19,
            autumnGrapes: 6.59,
            grannySmithApples: 3.99,
            honeyBellsTomatoes: 3.49,
            redDeliciousTomatoes: 2.99,
            idahoYellowPotatoes: 1.99,
            pomegranate: 2.99,
            strawberries: 2.75,
            greenPeppers: 1.50,
            pinkLadyApples: 4.29,
            organicBlackberries: 3.55,
            russetPotatoes: 1.89,
            blueberries: 2.99,
            mandarinOranges: 3.99,
            pineapple: 3.49,
            grapeTomatoes: 2.99,
            organicBlueberries: 3.99,
            grapeFruit: 5.49,
            jalapenoPeppers: 0.99,
            miniSweetPeppers: 3.36,
            organicCeleryHearts: 2.45,
            redPotatoes: 1.95,
            freshOrganicStrawberries: 5.99,
            cauliflowerCrowns: 3.23,
            limes: 0.79,
            heirloomTomatoes: 2.79,
            organicHoneyCrispApples: 2.99,
            organicGreenGrapes: 3.99,
            organicBananas: 0.59,
            lemons: 0.49,
            watermelon: 4.99,
            cantaloupe: 3.99,
            organicAvocados: 1.99,
            organicCarrots: 1.29,
            organicGrapeTomatoes: 3.49,
            radishes: 2.49,
            greenBrussels: 1.99,
            slicedMushrooms: 1.99,
            organicMiniCucumbers: 3.49,
            kiwi: 4.99,
            organicBroccoli: 2.99,
            organicPinkLadyApples: 4.89,
            sweetCorn: 2.29,
            bakingPotatoes: 3.49,
            limes: 2.49,
            celery: 1.99,
            whiteOnions: 2.39,
            cannedGrapeTomatoes: 2.49,
            cilantro: 0.89,
            bostonLettuce: 1.75,
            navelOranges: 0.99,
            gingerRoot: 2.19,
            seedlessCucumbers: 1.05,
            redOnions: 1.89,
            yellowPotatoes: 2.65,
            raspberries: 3.49,
            extraLargeEggs: 3.19,
            organicBabyCarrots: 1.99,
        }
    },
    {
        name: "Jewel Osco Naperville",
        distance: 1,
        location: { lat: 41.7908, lng: -88.1233 },
        prices: {
            bread: 3.6,
            banana: 0.87,
            rice: 5.20,
            apple: .30,
        }
    },
    // ... add other stores here
]; 